export const LANGUAGES = {
  id: {
    name: "Indonesia",
    title: "Secret Code Translator",
    loginInfo: "Silahkan masukkan username dan password akun jika sudah memiliki akun.",
    google: "🔵 Login Google",
    guest: "👤 Guest",
    username: "Username",
    password: "Password min. 6",
    register: "Buat akun",
    login: "Login",
    logout: "Keluar",
    translator: "Penerjemah",
    myCodes: "Kode Saya",
    history: "History",
    contact: "Hubungi Admin",
    admin: "Admin",
    translateTitle: "🔐 Penerjemah",
    textToCode: "Teks → Kode",
    codeToText: "Kode → Teks",
    saveHistory: "Simpan ke History",
    myCodesTitle: "⚙️ Kode Buatan Saya",
    myCodesInfo: "Contoh: A → @1. Kamu bebas menentukan aturan sendiri.",
    textOrLetter: "Teks/huruf",
    secretCode: "Kode rahasia",
    add: "Tambah",
    save: "Simpan",
    noCodes: "Belum ada kode.",
    contactTitle: "📩 Hubungi Admin",
    bug: "Bug / Error",
    question: "Pertanyaan",
    suggestion: "Saran",
    message: "Pesan",
    send: "Kirim",
    adminTitle: "🛡️ Admin",
    adminInfo: "Admin dapat melihat pengguna dan mengubah status.",
    usersMessages: "Pesan pengguna",
    noHistory: "Belum ada.",
    clearHistory: "Hapus History",
    active: "Aktif",
    suspended: "Suspend",
    banned: "Ban",
    sent: "Pesan terkirim.",
    saved: "Kode tersimpan.",
    language: "Bahasa"
  },
  en: {
    name: "English",
    title: "Secret Code Translator",
    loginInfo: "Please enter your username and password if you already have an account.",
    google: "🔵 Login with Google",
    guest: "👤 Guest",
    username: "Username",
    password: "Password min. 6",
    register: "Create account",
    login: "Login",
    logout: "Logout",
    translator: "Translator",
    myCodes: "My Codes",
    history: "History",
    contact: "Contact Admin",
    admin: "Admin",
    translateTitle: "🔐 Translator",
    textToCode: "Text → Code",
    codeToText: "Code → Text",
    saveHistory: "Save to History",
    myCodesTitle: "⚙️ My Custom Codes",
    myCodesInfo: "Example: A → @1. You can create your own rules.",
    textOrLetter: "Text/letter",
    secretCode: "Secret code",
    add: "Add",
    save: "Save",
    noCodes: "No codes yet.",
    contactTitle: "📩 Contact Admin",
    bug: "Bug / Error",
    question: "Question",
    suggestion: "Suggestion",
    message: "Message",
    send: "Send",
    adminTitle: "🛡️ Admin",
    adminInfo: "Admins can view users and change their status.",
    usersMessages: "User messages",
    noHistory: "No history yet.",
    clearHistory: "Clear History",
    active: "Active",
    suspended: "Suspend",
    banned: "Ban",
    sent: "Message sent.",
    saved: "Codes saved.",
    language: "Language"
  },
  ja: {
    name: "日本語",
    title: "Secret Code Translator",
    loginInfo: "アカウントをお持ちの場合は、ユーザー名とパスワードを入力してください。",
    google: "🔵 Googleでログイン",
    guest: "👤 ゲスト",
    username: "ユーザー名",
    password: "パスワード（6文字以上）",
    register: "アカウント作成",
    login: "ログイン",
    logout: "ログアウト",
    translator: "翻訳",
    myCodes: "マイコード",
    history: "履歴",
    contact: "管理者に連絡",
    admin: "管理者",
    translateTitle: "🔐 翻訳",
    textToCode: "テキスト → コード",
    codeToText: "コード → テキスト",
    saveHistory: "履歴に保存",
    myCodesTitle: "⚙️ カスタムコード",
    myCodesInfo: "例: A → @1。自分でルールを作れます。",
    textOrLetter: "テキスト/文字",
    secretCode: "秘密コード",
    add: "追加",
    save: "保存",
    noCodes: "コードはまだありません。",
    contactTitle: "📩 管理者に連絡",
    bug: "バグ / エラー",
    question: "質問",
    suggestion: "提案",
    message: "メッセージ",
    send: "送信",
    adminTitle: "🛡️ 管理者",
    adminInfo: "管理者はユーザーを確認し、ステータスを変更できます。",
    usersMessages: "ユーザーメッセージ",
    noHistory: "履歴はまだありません。",
    clearHistory: "履歴を削除",
    active: "有効",
    suspended: "停止",
    banned: "BAN",
    sent: "送信しました。",
    saved: "コードを保存しました。",
    language: "言語"
  },
  zh: {
    name: "中文",
    title: "Secret Code Translator",
    loginInfo: "如果您已有账号，请输入用户名和密码。",
    google: "🔵 使用 Google 登录",
    guest: "👤 访客",
    username: "用户名",
    password: "密码至少6位",
    register: "创建账户",
    login: "登录",
    logout: "退出",
    translator: "翻译器",
    myCodes: "我的代码",
    history: "历史记录",
    contact: "联系管理员",
    admin: "管理员",
    translateTitle: "🔐 翻译器",
    textToCode: "文本 → 代码",
    codeToText: "代码 → 文本",
    saveHistory: "保存到历史",
    myCodesTitle: "⚙️ 我的自定义代码",
    myCodesInfo: "例如：A → @1。你可以自由设置规则。",
    textOrLetter: "文本/字母",
    secretCode: "秘密代码",
    add: "添加",
    save: "保存",
    noCodes: "还没有代码。",
    contactTitle: "📩 联系管理员",
    bug: "错误 / Bug",
    question: "问题",
    suggestion: "建议",
    message: "消息",
    send: "发送",
    adminTitle: "🛡️ 管理员",
    adminInfo: "管理员可以查看用户并修改状态。",
    usersMessages: "用户消息",
    noHistory: "暂无历史记录。",
    clearHistory: "清除历史",
    active: "正常",
    suspended: "暂停",
    banned: "封禁",
    sent: "消息已发送。",
    saved: "代码已保存。",
    language: "语言"
  },
  es: {
    name: "Español",
    title: "Secret Code Translator",
    loginInfo: "Si ya tienes una cuenta, introduce tu nombre de usuario y contraseña.",
    google: "🔵 Iniciar sesión con Google",
    guest: "👤 Invitado",
    username: "Usuario",
    password: "Contraseña mín. 6",
    register: "Crear cuenta",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    translator: "Traductor",
    myCodes: "Mis códigos",
    history: "Historial",
    contact: "Contactar al administrador",
    admin: "Administrador",
    translateTitle: "🔐 Traductor",
    textToCode: "Texto → Código",
    codeToText: "Código → Texto",
    saveHistory: "Guardar en historial",
    myCodesTitle: "⚙️ Mis códigos personalizados",
    myCodesInfo: "Ejemplo: A → @1. Puedes crear tus propias reglas.",
    textOrLetter: "Texto/letra",
    secretCode: "Código secreto",
    add: "Añadir",
    save: "Guardar",
    noCodes: "Aún no hay códigos.",
    contactTitle: "📩 Contactar al administrador",
    bug: "Bug / Error",
    question: "Pregunta",
    suggestion: "Sugerencia",
    message: "Mensaje",
    send: "Enviar",
    adminTitle: "🛡️ Administrador",
    adminInfo: "Los administradores pueden ver usuarios y cambiar su estado.",
    usersMessages: "Mensajes de usuarios",
    noHistory: "Aún no hay historial.",
    clearHistory: "Borrar historial",
    active: "Activo",
    suspended: "Suspendido",
    banned: "Bloqueado",
    sent: "Mensaje enviado.",
    saved: "Códigos guardados.",
    language: "Idioma"
  }
};

export const getLanguage = () =>
  localStorage.getItem("sc_language") || "id";
